package scp.libraries.ui.utilities

// keep updated with mode enum in [attrs.xml]
const val SCP_VIEW_MODE_CONTAINMENT = 0
const val SCP_VIEW_MODE_DISRUPTION = 1
const val SCP_VIEW_MODE_RISK = 2


const val CONTAINMENT_CLASS_SAFE = 0
const val CONTAINMENT_CLASS_EUCLID = 1
const val CONTAINMENT_CLASS_KETER = 2
const val CONTAINMENT_CLASS_ESOTERIC = 3
const val CONTAINMENT_CLASS_NEUTRALIZED = 4
const val CONTAINMENT_CLASS_PENDING = 5
const val CONTAINMENT_CLASS_EXPLAINED = 6

const val DISRUPTION_CLASS_DARK = 1
const val DISRUPTION_CLASS_VLAM = 2
const val DISRUPTION_CLASS_KENEQ = 3
const val DISRUPTION_CLASS_EKHI = 4
const val DISRUPTION_CLASS_AMIDA = 5

const val RISK_CLASS_NOTICE = 1
const val RISK_CLASS_CAUTION = 2
const val RISK_CLASS_WARNING = 3
const val RISK_CLASS_DANGER = 4
const val RISK_CLASS_CRITICAL = 5

const val CLEARANCE_LEVEL_UNRESTRICTED = 1
const val CLEARANCE_LEVEL_RESTRICTED = 2
const val CLEARANCE_LEVEL_CONFIDENTIAL = 3
const val CLEARANCE_LEVEL_SECRET = 4
const val CLEARANCE_LEVEL_TOP_SECRET = 5
const val CLEARANCE_LEVEL_COSMIC_TOP_SECRET = 6

