@startuml
hide empty description

State ShowResultsState
State RoundInfoState
State PlayerTurnState
State PlayerPowerState
State PassDeviceState
State IntroState
State EndGameState
State CheckVictoryState
state CloseGameState


[*] --> IntroState
IntroState --> RoundInfoState: StartGameClicked

PassDeviceState --> PlayerTurnState: PassedToPlayerClicked

PlayerPowerState --> ShowResultsState: EndRoundClicked
PlayerPowerState --> PassDeviceState: EndTurnClicked

PlayerTurnState --> ShowResultsState: EndRoundClicked
PlayerTurnState --> PassDeviceState: EndTurnClicked
PlayerTurnState --> PlayerPowerState: PlayTurnClicked

RoundInfoState --> PassDeviceState: StartDayRoundClicked,\nStartNightRoundClicked

ShowResultsState --> CheckVictoryState: ResultSeenClicked

CheckVictoryState --> EndGameState: VictoryReached
CheckVictoryState --> RoundInfoState: StartDayRoundClicked,\nStartNightRoundClicked

EndGameState --> CloseGameState: CloseGameClicked

CloseGameState --> [*]

@enduml
